### ISSUE TITLE
ロゴを作成する

### ISSUE THREAD

**Issue by shimadam** [sota1235/Party#22]
「感謝祭！ ~これを知らないと社員失格よ★ 七不思議~」

**Comment by sota1235** [comment]
(一応パブリックリポジトリなので固有名詞はissueで避けてくれると…(｡ŏ﹏ŏ))

**Comment by shimadam** [comment]
(なるほど・・・失礼しました・・・:fearful:)

**Comment by sota1235** [comment]
汎用的にしたいので簡単に差し替えられる方向性で作る

**Comment by sota1235** [comment]
config等で読み込ませる

**Comment by sota1235** [comment]
done.
