### ISSUE TITLE
正解演出のCSS/JSを作る

### ISSUE THREAD

**Issue by sota1235** [sota1235/Party#8]
派手にいこう

**Comment by shimadam** [comment]
∧__∧
　　　 （ ｀･ω･  ） ・・・開幕ぜよ
　　　.ノ^　yヽ、
　　　ヽ,,ﾉ==l ﾉ 　
　　　　/ 　l |
"""~""""""~"""~"""~"

**Comment by sota1235** [comment]
素晴らしい。
https://daneden.github.io/animate.css/

**Comment by sota1235** [comment]
done
